In [1]:
import pandas as pd
from datetime import datetime

# Extract the information

The extract process needed to be manual, due to the CNBV doesn't count with an API and the downloadable file creates a pivot table on an Excel file that can't be handled

In [2]:
# Load the file
data=pd.read_excel("data/20210308Data.xlsx")

In [3]:
data.shape

(29825, 245)

In [4]:
data.head()

,cve_institucion,cve_concepto,200012,200101,200102,200103,200104,200105,200106,200107,...,202005,202006,202007,202008,202009,202010,202011,202012,202101,Grand Total
0,040002,1.000000e+11,404155.539381,394339.144611,398165.969974,396748.807840,394034.682061,397417.906353,390335.530120,397125.976484,...,1.403779e+06,1.400146e+06,1.431086e+06,1.403597e+06,1.375992e+06,1.358075e+06,1.329905e+06,1.356419e+06,1.365755e+06,2.272193e+08
1,NaN,1.100000e+11,25111.100235,24510.989273,22223.129407,25016.224513,22234.320323,24171.781379,23781.683570,21860.687917,...,8.967279e+04,7.474442e+04,1.158531e+05,1.205825e+05,8.548155e+04,8.912308e+04,8.313712e+04,1.330061e+05,1.214763e+05,2.069009e+07
2,NaN,1.101000e+11,7748.399076,4300.860578,4400.047667,4121.606296,4484.620863,4713.212818,4276.527457,4296.573284,...,2.844347e+04,2.589051e+04,2.932586e+04,2.582749e+04,2.410493e+04,2.534144e+04,2.930508e+04,3.326624e+04,3.001014e+04,3.588940e+06
3,NaN,1.102000e+11,16499.943715,19677.001561,17297.767938,20293.765145,17269.417648,19012.391525,19147.689422,17067.406522,...,1.491724e+04,1.527481e+04,-6.634663e+03,9.287726e+03,-7.082801e+03,-2.207891e+04,-9.899074e+03,1.222358e+04,2.066360e+04,-1.754574e+06
4,NaN,1.103000e+11,344.422987,272.065783,267.612960,278.623623,298.010203,259.137843,178.403780,343.666844,...,1.715925e+03,2.166395e+03,2.044062e+03,2.643912e+03,2.243062e+03,1.733480e+03,2.016134e+03,8.095555e+02,1.163158e+03,1.382839e+05

# Transform

* From the pivot table the column cve_institucion only have the first value for each Bank, so we need to complete the empty fields with the same information and we use the "front fill method"
* Get the columns that represent the years and drop the empty ones

In [5]:
# fill the empty spaces
data[["cve_institucion"]] = data[["cve_institucion"]].fillna(method="ffill")
data

,cve_institucion,cve_concepto,200012,200101,200102,200103,200104,200105,200106,200107,...,202005,202006,202007,202008,202009,202010,202011,202012,202101,Grand Total
0,040002,1.000000e+11,4.041555e+05,3.943391e+05,3.981660e+05,3.967488e+05,3.940347e+05,3.974179e+05,3.903355e+05,3.971260e+05,...,1.403779e+06,1.400146e+06,1.431086e+06,1.403597e+06,1.375992e+06,1.358075e+06,1.329905e+06,1.356419e+06,1.365755e+06,2.272193e+08
1,040002,1.100000e+11,2.511110e+04,2.451099e+04,2.222313e+04,2.501622e+04,2.223432e+04,2.417178e+04,2.378168e+04,2.186069e+04,...,8.967279e+04,7.474442e+04,1.158531e+05,1.205825e+05,8.548155e+04,8.912308e+04,8.313712e+04,1.330061e+05,1.214763e+05,2.069009e+07
2,040002,1.101000e+11,7.748399e+03,4.300861e+03,4.400048e+03,4.121606e+03,4.484621e+03,4.713213e+03,4.276527e+03,4.296573e+03,...,2.844347e+04,2.589051e+04,2.932586e+04,2.582749e+04,2.410493e+04,2.534144e+04,2.930508e+04,3.326624e+04,3.001014e+04,3.588940e+06
3,040002,1.102000e+11,1.649994e+04,1.967700e+04,1.729777e+04,2.029377e+04,1.726942e+04,1.901239e+04,1.914769e+04,1.706741e+04,...,1.491724e+04,1.527481e+04,-6.634663e+03,9.287726e+03,-7.082801e+03,-2.207891e+04,-9.899074e+03,1.222358e+04,2.066360e+04,-1.754574e+06
4,040002,1.103000e+11,3.444230e+02,2.720658e+02,2.676130e+02,2.786236e+02,2.980102e+02,2.591378e+02,1.784038e+02,3.436668e+02,...,1.715925e+03,2.166395e+03,2.044062e+03,2.643912e+03,2.243062e+03,1.733480e+03,2.016134e+03,8.095555e+02,1.163158e+03,1.382839e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29820,99,6.706000e+11,1.299145e+02,1.649774e+01,3.362601e+01,4.130833e+01,6.155691e+01,7.834090e+01,9.155453e+01,1.019147e+02,...,1.439397e+03,1.664318e+03,1.919260e+03,2.163582e+03,2.433676e+03,2.624965e+03,2.774753e+03,2.931714e+03,2.636747e+02,1.467606e+05
29821,99,6.711000e+11,1.333846e+02,1.720747e+01,3.541598e+01,4.724513e+01,7.146511e+01,9.088076e+01,1.076853e+02,1.193678e+02,...,1.439397e+03,1.664318e+03,1.919260e+03,2.163582e+03,2.433676e+03,2.624965e+03,2.774753e+03,2.931714e+03,2.636747e+02,1.488927e+05
29822,99,8.000000e+11,1.114730e+04,1.159498e+04,1.114110e+04,1.114697e+04,1.161195e+04,1.248901e+04,1.180374e+04,1.222692e+04,...,1.435443e+05,1.467765e+05,1.462839e+05,1.458156e+05,1.471399e+05,1.515761e+05,1.472387e+05,1.498860e+05,1.492822e+05,1.516581e+07
29823,99 Total,NaN,8.305512e+04,7.680495e+04,7.441272e+04,7.512943e+04,7.880314e+04,8.468307e+04,8.075756e+04,8.352717e+04,...,1.183298e+06,1.212908e+06,1.211297e+06,1.216791e+06,1.232590e+06,1.264071e+06,1.242819e+06,1.268971e+06,1.185572e+06,1.209830e+08
29824,Grand Total,NaN,7.002391e+07,6.084185e+07,6.265189e+07,6.399945e+07,6.415659e+07,6.584799e+07,6.783114e+07,6.962590e+07,...,5.724594e+08,5.777929e+08,5.756197e+08,5.707967e+08,5.682973e+08,5.706007e+08,5.704813e+08,5.677238e+08,5.427077e+08,6.309957e+10

In [6]:
# Get the YearMonth columns to check only empty rows in this columns
cols = data.columns
cols = cols[2:-1]
cols

Index([200012, 200101, 200102, 200103, 200104, 200105, 200106, 200107, 200108,
       200109,
       ...
       202004, 202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012,
       202101],
      dtype='object', length=242)

In [7]:
data_clean = data.drop_duplicates(subset=cols, keep=False)
data_clean

,cve_institucion,cve_concepto,200012,200101,200102,200103,200104,200105,200106,200107,...,202005,202006,202007,202008,202009,202010,202011,202012,202101,Grand Total
0,040002,1.000000e+11,4.041555e+05,3.943391e+05,3.981660e+05,3.967488e+05,3.940347e+05,3.974179e+05,3.903355e+05,3.971260e+05,...,1.403779e+06,1.400146e+06,1.431086e+06,1.403597e+06,1.375992e+06,1.358075e+06,1.329905e+06,1.356419e+06,1.365755e+06,2.272193e+08
1,040002,1.100000e+11,2.511110e+04,2.451099e+04,2.222313e+04,2.501622e+04,2.223432e+04,2.417178e+04,2.378168e+04,2.186069e+04,...,8.967279e+04,7.474442e+04,1.158531e+05,1.205825e+05,8.548155e+04,8.912308e+04,8.313712e+04,1.330061e+05,1.214763e+05,2.069009e+07
3,040002,1.102000e+11,1.649994e+04,1.967700e+04,1.729777e+04,2.029377e+04,1.726942e+04,1.901239e+04,1.914769e+04,1.706741e+04,...,1.491724e+04,1.527481e+04,-6.634663e+03,9.287726e+03,-7.082801e+03,-2.207891e+04,-9.899074e+03,1.222358e+04,2.066360e+04,-1.754574e+06
4,040002,1.103000e+11,3.444230e+02,2.720658e+02,2.676130e+02,2.786236e+02,2.980102e+02,2.591378e+02,1.784038e+02,3.436668e+02,...,1.715925e+03,2.166395e+03,2.044062e+03,2.643912e+03,2.243062e+03,1.733480e+03,2.016134e+03,8.095555e+02,1.163158e+03,1.382839e+05
14,040002,1.208000e+11,3.415957e+03,2.027871e+02,2.825408e+03,2.801145e+03,3.849574e+03,7.965415e+03,6.618112e+03,1.024196e+04,...,1.000000e-06,1.000000e-06,1.000000e-06,1.000127e+04,2.000000e-06,2.000000e-06,2.000000e-06,1.500183e+04,1.000368e+04,2.332709e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29820,99,6.706000e+11,1.299145e+02,1.649774e+01,3.362601e+01,4.130833e+01,6.155691e+01,7.834090e+01,9.155453e+01,1.019147e+02,...,1.439397e+03,1.664318e+03,1.919260e+03,2.163582e+03,2.433676e+03,2.624965e+03,2.774753e+03,2.931714e+03,2.636747e+02,1.467606e+05
29821,99,6.711000e+11,1.333846e+02,1.720747e+01,3.541598e+01,4.724513e+01,7.146511e+01,9.088076e+01,1.076853e+02,1.193678e+02,...,1.439397e+03,1.664318e+03,1.919260e+03,2.163582e+03,2.433676e+03,2.624965e+03,2.774753e+03,2.931714e+03,2.636747e+02,1.488927e+05
29822,99,8.000000e+11,1.114730e+04,1.159498e+04,1.114110e+04,1.114697e+04,1.161195e+04,1.248901e+04,1.180374e+04,1.222692e+04,...,1.435443e+05,1.467765e+05,1.462839e+05,1.458156e+05,1.471399e+05,1.515761e+05,1.472387e+05,1.498860e+05,1.492822e+05,1.516581e+07
29823,99 Total,NaN,8.305512e+04,7.680495e+04,7.441272e+04,7.512943e+04,7.880314e+04,8.468307e+04,8.075756e+04,8.352717e+04,...,1.183298e+06,1.212908e+06,1.211297e+06,1.216791e+06,1.232590e+06,1.264071e+06,1.242819e+06,1.268971e+06,1.185572e+06,1.209830e+08
29824,Grand Total,NaN,7.002391e+07,6.084185e+07,6.265189e+07,6.399945e+07,6.415659e+07,6.584799e+07,6.783114e+07,6.962590e+07,...,5.724594e+08,5.777929e+08,5.756197e+08,5.707967e+08,5.682973e+08,5.706007e+08,5.704813e+08,5.677238e+08,5.427077e+08,6.309957e+10

In [8]:
# After cleaning the dataframe we get a lighter dataframe
print(f"Initial: ${data.shape} - Now: ${data_clean.shape}")

Initial: $(29825, 245) - Now: $(12314, 245)

In [9]:
# Drop the rows where the cve_institucion is empty
data_clean = data_clean.dropna(subset=["cve_concepto"])
data_clean

,cve_institucion,cve_concepto,200012,200101,200102,200103,200104,200105,200106,200107,...,202005,202006,202007,202008,202009,202010,202011,202012,202101,Grand Total
0,040002,1.000000e+11,404155.539381,394339.144611,398165.969974,396748.807840,394034.682061,397417.906353,390335.530120,397125.976484,...,1.403779e+06,1.400146e+06,1.431086e+06,1.403597e+06,1.375992e+06,1.358075e+06,1.329905e+06,1.356419e+06,1.365755e+06,2.272193e+08
1,040002,1.100000e+11,25111.100235,24510.989273,22223.129407,25016.224513,22234.320323,24171.781379,23781.683570,21860.687917,...,8.967279e+04,7.474442e+04,1.158531e+05,1.205825e+05,8.548155e+04,8.912308e+04,8.313712e+04,1.330061e+05,1.214763e+05,2.069009e+07
3,040002,1.102000e+11,16499.943715,19677.001561,17297.767938,20293.765145,17269.417648,19012.391525,19147.689422,17067.406522,...,1.491724e+04,1.527481e+04,-6.634663e+03,9.287726e+03,-7.082801e+03,-2.207891e+04,-9.899074e+03,1.222358e+04,2.066360e+04,-1.754574e+06
4,040002,1.103000e+11,344.422987,272.065783,267.612960,278.623623,298.010203,259.137843,178.403780,343.666844,...,1.715925e+03,2.166395e+03,2.044062e+03,2.643912e+03,2.243062e+03,1.733480e+03,2.016134e+03,8.095555e+02,1.163158e+03,1.382839e+05
14,040002,1.208000e+11,3415.956580,202.787125,2825.408258,2801.145130,3849.574083,7965.414625,6618.111587,10241.955967,...,1.000000e-06,1.000000e-06,1.000000e-06,1.000127e+04,2.000000e-06,2.000000e-06,2.000000e-06,1.500183e+04,1.000368e+04,2.332709e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29818,99,6.704000e+11,174.299818,22.120968,39.127718,57.707489,83.739835,107.294659,116.006431,133.020527,...,1.993946e+03,2.300771e+03,2.653124e+03,2.987166e+03,3.344076e+03,3.619554e+03,3.838190e+03,4.069620e+03,3.649076e+02,1.964650e+05
29819,99,6.705000e+11,177.398473,22.292038,43.976094,63.087548,88.722411,122.419332,133.186439,151.053718,...,2.003632e+03,2.316091e+03,2.667906e+03,3.002514e+03,3.378277e+03,3.653061e+03,3.871196e+03,4.101078e+03,3.682855e+02,2.018406e+05
29820,99,6.706000e+11,129.914544,16.497738,33.626007,41.308328,61.556913,78.340898,91.554527,101.914731,...,1.439397e+03,1.664318e+03,1.919260e+03,2.163582e+03,2.433676e+03,2.624965e+03,2.774753e+03,2.931714e+03,2.636747e+02,1.467606e+05
29821,99,6.711000e+11,133.384636,17.207470,35.415983,47.245135,71.465107,90.880756,107.685297,119.367773,...,1.439397e+03,1.664318e+03,1.919260e+03,2.163582e+03,2.433676e+03,2.624965e+03,2.774753e+03,2.931714e+03,2.636747e+02,1.488927e+05
29822,99,8.000000e+11,11147.303886,11594.977118,11141.104553,11146.965614,11611.953357,12489.006858,11803.744263,12226.918474,...,1.435443e+05,1.467765e+05,1.462839e+05,1.458156e+05,1.471399e+05,1.515761e+05,1.472387e+05,1.498860e+05,1.492822e+05,1.516581e+07

In [10]:
# check for null or na values
data_clean["cve_institucion"] = data_clean["cve_institucion"].astype(str)
data_clean["cve_institucion"].unique()

<ipython-input-10-45ce3455a2fc>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean["cve_institucion"] = data_clean["cve_institucion"].astype(str)

array(['040002', '040003', '040004', '040007', '040008', '040012',
       '040013', '040014', '040016', '040017', '040021', '040022',
       '040025', '040028', '040030', '040032', '040036', '040037',
       '040042', '040044', '040056', '040058', '040059', '040060',
       '040062', '040065', '040072', '040083', '040086', '040101',
       '040102', '040103', '040106', '040107', '040108', '040109',
       '040110', '040112', '040113', '040114', '040116', '040117',
       '040119', '040124', '040126', '040127', '040128', '040129',
       '040130', '040131', '040132', '040133', '040134', '040136',
       '040137', '040138', '040139', '040140', '040141', '040142',
       '040143', '040144', '040145', '040146', '040147', '040148',
       '040149', '040150', '040151', '040152', '040154', '040155',
       '040156', '040157', '040158', '040159', '040160', '040161',
       '040162', '040163', '102', '112', '114', '128', '130', '132',
       '136', '143', '144', '145', '152', '156', '158', '159', '162',
       '172', '21', '5', '59', '60', '61', '62', '63', '65', '66', '67',
       '68', '69', '80', '81', '82', '83', '84', '85', '86', '91', '92',
       '93', '94', '95', '96', '97', '98', '99'], dtype=object)

In [11]:
# check for null or na values
data_clean["cve_concepto"].unique()

array([1.00000000e+11, 1.10000000e+11, 1.10200000e+11, 1.10300000e+11,
       1.20800000e+11, 1.21000000e+11, 1.30000000e+11, 1.30100000e+11,
       1.30105000e+11, 1.30105010e+11, 1.30105020e+11, 1.30105060e+11,
       1.30106000e+11, 1.30106010e+11, 1.30106020e+11, 1.30106900e+11,
       1.30115020e+11, 1.30121000e+11, 1.30121010e+11, 1.30121020e+11,
       1.30121030e+11, 1.30121040e+11, 1.31100000e+11, 1.31101000e+11,
       1.31112000e+11, 1.31114000e+11, 1.31123000e+11, 1.31190000e+11,
       1.31601000e+11, 1.31602000e+11, 1.31690000e+11, 1.35000000e+11,
       1.35100000e+11, 1.35105000e+11, 1.35105010e+11, 1.35105040e+11,
       1.35105060e+11, 1.35156000e+11, 1.35156010e+11, 1.35156020e+11,
       1.35156900e+11, 1.35171000e+11, 1.35171010e+11, 1.35171020e+11,
       1.35171030e+11, 1.35171040e+11, 1.36100000e+11, 1.36101000e+11,
       1.36103000e+11, 1.36106000e+11, 1.36113000e+11, 1.36690000e+11,
       1.39000000e+11, 1.39150510e+11, 1.39150511e+11, 1.39150610e+11,
       1.39150670e+11, 1.39150670e+11, 1.39150670e+11, 1.39150671e+11,
       1.39150671e+11, 1.39150679e+11, 1.39150770e+11, 1.39150770e+11,
       1.39201000e+11, 1.39201050e+11, 1.39201060e+11, 1.39201710e+11,
       1.39202000e+11, 1.39202020e+11, 1.39202040e+11, 1.39202900e+11,
       1.39203000e+11, 1.39290000e+11, 1.39600000e+11, 1.50000000e+11,
       1.70000000e+11, 1.80000000e+11, 1.90000000e+11, 2.00000000e+11,
       2.03000000e+11, 2.10100000e+11, 2.20700000e+11, 2.30000000e+11,
       2.30200000e+11, 2.30300000e+11, 2.70000000e+11, 2.90000000e+11,
       4.00000000e+11, 4.20000000e+11, 4.20100000e+11, 4.20200000e+11,
       4.20300000e+11, 5.05000000e+11, 5.10000000e+11, 5.10000000e+11,
       5.10100000e+11, 5.10200000e+11, 5.10300000e+11, 5.10501050e+11,
       5.10501060e+11, 5.10501210e+11, 5.10511000e+11, 5.10511010e+11,
       5.10511900e+11, 5.10600000e+11, 5.10651000e+11, 5.30000000e+11,
       5.32101000e+11, 5.32101050e+11, 5.32101060e+11, 5.32101210e+11,
       5.32111000e+11, 5.32111010e+11, 5.32111010e+11, 5.32111010e+11,
       5.32111130e+11, 5.32166000e+11, 5.40000000e+11, 5.40000000e+11,
       5.50000000e+11, 5.60000000e+11, 5.70000000e+11, 5.80000000e+11,
       6.10000000e+11, 6.10000000e+11, 6.10100000e+11, 6.10600000e+11,
       6.11400000e+11, 6.20000000e+11, 6.29151000e+11, 6.29151050e+11,
       6.29151060e+11, 6.29161000e+11, 6.30000000e+11, 6.40000000e+11,
       6.50000000e+11, 6.60000000e+11, 6.70200000e+11, 6.70200000e+11,
       6.70300000e+11, 6.70400000e+11, 6.70500000e+11, 6.70600000e+11,
       6.71100000e+11, 8.00000000e+11, 1.10100000e+11, 1.20000000e+11,
       1.20100000e+11, 1.20100040e+11, 1.20101000e+11, 1.20200000e+11,
       1.20201000e+11, 1.21400000e+11, 1.21500000e+11, 1.31102000e+11,
       1.31600000e+11, 1.36102000e+11, 1.36190000e+11, 1.36600000e+11,
       1.36601000e+11, 1.36602000e+11, 1.39150510e+11, 1.39150517e+11,
       1.39150660e+11, 1.60000000e+11, 2.11100000e+11, 2.11101000e+11,
       2.11102000e+11, 2.20000000e+11, 2.20800000e+11, 2.21400000e+11,
       2.21500000e+11, 2.30100000e+11, 4.10000000e+11, 4.20400000e+11,
       4.21200000e+11, 5.10516000e+11, 6.10200000e+11, 6.10300000e+11,
       1.39202030e+11, 5.10661000e+11, 5.32111030e+11, 1.20700000e+11,
       1.30105030e+11, 1.30105070e+11, 1.31113000e+11, 1.31603000e+11,
       1.35105020e+11, 1.35105030e+11, 1.36105000e+11, 1.36603000e+11,
       1.39150770e+11, 1.39202070e+11, 2.20900000e+11, 2.21700000e+11,
       5.10671000e+11, 5.32111900e+11, 6.29151210e+11, 6.29166000e+11,
       6.10400000e+11, 1.10405000e+11, 1.15000000e+11, 1.30105040e+11,
       1.30105080e+11, 1.30121050e+11, 1.35105070e+11, 1.35105080e+11,
       1.39202010e+11, 1.79700000e+11, 1.79701000e+11, 2.11103000e+11,
       2.75000000e+11, 6.10700000e+11, 1.21700000e+11, 4.30000000e+11,
       1.30105050e+11, 1.35105050e+11, 1.79702000e+11, 1.31104000e+11,
       1.36104000e+11, 1.39150670e+11, 1.39202050e+11, 2.21900000e+11,
       1.31604000e+11, 1.36604000e+11, 1.39150770e+11, 5.32111020e+11,
       5.32111050e+11])

In [12]:
# Filter data important for the project

#130000000000 = Cartera de crÃ©dito vigente
#130100000000 = CrÃ©ditos comerciales
#131100000000 = Consumo
#131600000000 = Vivienda
#200000000000 = Pasivo
#210100000000 = DepÃ³sitos de exigibilidad inmediata
#211100000000 = DepÃ³sitos a plazo y tÃ­tulos de crÃ©dito emitidos 
cves = [510000000000,610000000000,620000000000,670200000000,640000000000,
        670500000000,671100000000,110000000000,130100000000,
        130105000000,130106000000,130121000000,131100000000,131101000000,
        131199990000,131600000000,200000000000,210100000000,211100000000]

filter_cve = data_clean["cve_concepto"] == 100000000000
data_filtered = data_clean.loc[filter_cve]

for cve in cves:
    filter_cve = data_clean["cve_concepto"] == cve
    data_filtered = data_filtered.append(data_clean.loc[filter_cve])

In [13]:
data_filtered.shape

(1669, 245)

In [14]:
#get columns for the time
clean_cols = data_filtered.columns
clean_cols = clean_cols[2:-1]
clean_cols

Index([200012, 200101, 200102, 200103, 200104, 200105, 200106, 200107, 200108,
       200109,
       ...
       202004, 202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012,
       202101],
      dtype='object', length=242)

In [15]:
#rename the columns to add a prefix "value" so then we can make the wide_to_long
for column in clean_cols:
    data_filtered = data_filtered.rename(columns={
        column: f"value{column}" 
    })

In [16]:
#check if it was done properly
data_filtered.columns

Index(['cve_institucion', 'cve_concepto', 'value200012', 'value200101',
       'value200102', 'value200103', 'value200104', 'value200105',
       'value200106', 'value200107',
       ...
       'value202005', 'value202006', 'value202007', 'value202008',
       'value202009', 'value202010', 'value202011', 'value202012',
       'value202101', 'Grand Total'],
      dtype='object', length=245)

In [17]:
# wide_to_long transformation so we have a vertical table with time series and values
data_filtered = pd.wide_to_long(data_filtered, stubnames='value', i=['cve_institucion', 'cve_concepto'], j='time')

In [18]:
#reset index to have our 3 columns in dataframe
data_filtered = data_filtered.reset_index()
data_filtered

       cve_institucion  cve_concepto    time   Grand Total          value
0               040002  1.000000e+11  200012  2.272193e+08  404155.539381
1               040002  1.000000e+11  200101  2.272193e+08  394339.144611
2               040002  1.000000e+11  200102  2.272193e+08  398165.969974
3               040002  1.000000e+11  200103  2.272193e+08  396748.807840
4               040002  1.000000e+11  200104  2.272193e+08  394034.682061
...                ...           ...     ...           ...            ...
403893              99  2.111000e+11  202009  4.617976e+06   54072.492055
403894              99  2.111000e+11  202010  4.617976e+06   53401.786429
403895              99  2.111000e+11  202011  4.617976e+06   53212.081144
403896              99  2.111000e+11  202012  4.617976e+06   54091.203091
403897              99  2.111000e+11  202101  4.617976e+06   51071.528918

[403898 rows x 5 columns]

In [19]:
del data_filtered["Grand Total"]

In [20]:
# put the column time in time type data
data_filtered["time"] = pd.to_datetime(data_filtered["time"],format="%Y%m")

In [21]:
data_filtered["value"] = data_filtered["value"].fillna(0)

In [22]:
data_filtered

       cve_institucion  cve_concepto       time          value
0               040002  1.000000e+11 2000-12-01  404155.539381
1               040002  1.000000e+11 2001-01-01  394339.144611
2               040002  1.000000e+11 2001-02-01  398165.969974
3               040002  1.000000e+11 2001-03-01  396748.807840
4               040002  1.000000e+11 2001-04-01  394034.682061
...                ...           ...        ...            ...
403893              99  2.111000e+11 2020-09-01   54072.492055
403894              99  2.111000e+11 2020-10-01   53401.786429
403895              99  2.111000e+11 2020-11-01   53212.081144
403896              99  2.111000e+11 2020-12-01   54091.203091
403897              99  2.111000e+11 2021-01-01   51071.528918

[403898 rows x 4 columns]

In [23]:
# Save the file to continue cleaning in different sessions
data_filtered.to_csv("data/data_filtered.csv")

In [ ]:
#data_clean = pd.read_csv("data/data_clean.csv")

# Load

Load the files into an AWS PostgreSQL Database

In [ ]:
from sqlalchemy import create_engine

In [ ]:
#connection string for AWS PostgreSQL
endpoint = "banking.cephpaqhv83w.us-east-2.rds.amazonaws.com"
conn = f"postgresql+psycopg2://postgres:2gZq7GdZ7Nw8iuAoRufq@{endpoint}:5432/banking"

In [ ]:
#Create the engine
engine = create_engine(conn)

In [ ]:
#Save the clean data to the database
data_filtered.to_sql("data_filtered", engine, if_exists="replace")

In [ ]:
# TooManyColumns: tables can have at most 1600 columns
# data_clean_transpose.to_sql("data_transpose", engine, if_exists="replace")

In [ ]:
conceptos = pd.read_excel("data/Book6.xlsx")
conceptos = conceptos.dropna()
conceptos

In [ ]:
conceptos.to_sql("conceptos", engine, if_exists="replace")

In [ ]:
bancos = pd.read_excel("data/Book6.xlsx", sheet_name='Sheet2')
#bancos = bancos.dropna()
bancos

In [ ]:
bancos.to_sql("banks", engine, if_exists="replace")

In [ ]:
test = pd.read_sql("""SELECT * 
FROM data_clean 
WHERE cve_institucion IN ('21','102')
AND cve_concepto IN ( SELECT CAST (cve_concepto AS TEXT ) FROM conceptos )""",engine)

In [ ]:
#del test["Grand Total"]
test

In [ ]:
test_cols = test.columns
test_cols = test_cols[2:-1]
test_cols

In [ ]:
for column in test_cols:
    test = test.rename(columns={
        column: f"value{column}"
    })

In [ ]:
#test = test.fillna(0)

In [ ]:
tes2 = pd.melt(test, id_vars=['cve_institucion', 'cve_concepto'],
               value_vars=test_cols, value_name="value", var_name="time")

In [ ]:
test2

In [ ]:
test2 = pd.wide_to_long(test, stubnames='value', i=['cve_institucion', 'cve_concepto'], j='time')

In [ ]:
test2